# Generated by Django 6.1.1 on 2026-09-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
