# Generated by Django 6.1.1 on 2026-09-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_bookmark_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
